---
- name: geerlingguy.repo-epel
  src: git@github.com:geerlingguy/ansible-role-repo-epel.git
  scm: git
  version: 1.2.3
- name: geerlingguy.pip
  src: git@github.com:geerlingguy/ansible-role-pip.git
  scm: git
  version: 1.3.0
- name: geerlingguy.docker
  src: git@github.com:geerlingguy/ansible-role-docker.git
  scm: git
  version: 2.5.2